-- Insert a test AC product with 1 rupee price
INSERT INTO public.products (
  name,
  model,
  series,
  brand,
  tonnage,
  price,
  original_price,
  discount_percent,
  star_rating,
  review_count,
  features,
  description,
  specifications,
  image_urls,
  is_available,
  is_featured,
  energy_rating,
  warranty_years,
  slug,
  seo_title,
  seo_description
) VALUES (
  'Test AC - 1 Rupee Special',
  'TEST-001',
  'Testing Series',
  'Voltas',
  1.0,
  1,
  2000,
  99,
  4.5,
  100,
  ARRAY['Energy Efficient', 'Silent Operation', 'Quick Cooling', 'Anti-Bacterial Filter', 'Remote Control'],
  'This is a test AC product with 1 rupee price for testing payment integration.',
  '{"cooling_capacity": "1 Ton", "power_consumption": "900W", "refrigerant": "R32", "noise_level": "45dB", "dimensions": "80x60x25 cm"}'::jsonb,
  ARRAY['/src/assets/split-ac.jpg'],
  true,
  true,
  '5 Star',
  2,
  'test-ac-1-rupee',
  'Test AC - 1 Rupee Special | Khandelwal Distributors',
  'Test AC product with 1 rupee price for payment testing. Energy efficient cooling solution.'
);